DROP TABLE IF EXISTS base_table_temp;	CREATE TABLE base_table_temp(		Txn_Id VARCHAR(24),		Txn_Type VARCHAR(24),		Txn_Status VARCHAR(24), 		Sttlmnt_Dt DATETIME NULL,		Disbursement_Dt DATETIME,		Auth_Amt FLOAT,		Settled_Amt FLOAT,		Refund_Txn_Id VARCHAR(24),		Payment_Type VARCHAR(24),		Card_Type VARCHAR(24),		CC_Number VARCHAR(24),		Billing_Postal_Code VARCHAR(24),		Billing_Country VARCHAR(24),		Shipping_Postal_Code VARCHAR(24),		Shipping_Country VARCHAR(24),		IP_Addr VARCHAR(24),		Processor_Response_Code FLOAT,		Settlement_Currency VARCHAR(24),		PRIMARY KEY ( Txn_Id )	)	;
INSERT INTO base_table_temp (Txn_Id, Txn_Type, Txn_Status, Sttlmnt_Dt, Disbursement_Dt, Auth_Amt, Settled_Amt, Refund_Txn_Id, Payment_Type, Card_Type, CC_Number, Billing_Postal_Code, Billing_Country, Shipping_Postal_Code, Shipping_Country, IP_Addr, Processor_Response_Code, Settlement_Currency) VALUES ('1xcbvrpy', 'sale', 'settled', '12/11/18', '12/12/18', 1.29, 1.29, '', 'Credit Card', 'Visa', '##########', 'X', 'United States of America', '', '', '192.237.212.164', 1000.0, 'USD');
INSERT INTO base_table_temp (Txn_Id, Txn_Type, Txn_Status, Sttlmnt_Dt, Disbursement_Dt, Auth_Amt, Settled_Amt, Refund_Txn_Id, Payment_Type, Card_Type, CC_Number, Billing_Postal_Code, Billing_Country, Shipping_Postal_Code, Shipping_Country, IP_Addr, Processor_Response_Code, Settlement_Currency) VALUES ('2nk2hgjy', 'sale', 'settled', '12/13/18', '12/14/18', 8.41, 8.41, '', 'Credit Card', 'MasterCard', '##########', 'X', 'United States of America', '', '', '192.237.212.164', 1000.0, 'USD');
INSERT INTO base_table_temp (Txn_Id, Txn_Type, Txn_Status, Sttlmnt_Dt, Disbursement_Dt, Auth_Amt, Settled_Amt, Refund_Txn_Id, Payment_Type, Card_Type, CC_Number, Billing_Postal_Code, Billing_Country, Shipping_Postal_Code, Shipping_Country, IP_Addr, Processor_Response_Code, Settlement_Currency) VALUES ('47wjpd20', 'sale', 'settled', '12/11/18', '12/12/18', 3.67, 3.67, '', 'Credit Card', 'MasterCard', '##########', 'X', 'United States of America', '', '', '192.237.212.164', 1000.0, 'USD');
INSERT INTO base_table_temp (Txn_Id, Txn_Type, Txn_Status, Sttlmnt_Dt, Disbursement_Dt, Auth_Amt, Settled_Amt, Refund_Txn_Id, Payment_Type, Card_Type, CC_Number, Billing_Postal_Code, Billing_Country, Shipping_Postal_Code, Shipping_Country, IP_Addr, Processor_Response_Code, Settlement_Currency) VALUES ('5013smqh', 'sale', 'settled', '12/13/18', '12/14/18', 1.18, 1.18, '', 'Credit Card', 'Visa', '##########', 'X', 'United States of America', '', '', '192.237.212.164', 1000.0, 'USD');
INSERT INTO base_table_temp (Txn_Id, Txn_Type, Txn_Status, Sttlmnt_Dt, Disbursement_Dt, Auth_Amt, Settled_Amt, Refund_Txn_Id, Payment_Type, Card_Type, CC_Number, Billing_Postal_Code, Billing_Country, Shipping_Postal_Code, Shipping_Country, IP_Addr, Processor_Response_Code, Settlement_Currency) VALUES ('5yxx6jy9', 'sale', 'settled', '12/3/18', '12/4/18', 9.91, 9.91, '', 'Credit Card', 'Visa', '##########', 'X', 'United States of America', '', '', '192.237.212.164', 1000.0, 'USD');
INSERT INTO base_table_temp (Txn_Id, Txn_Type, Txn_Status, Sttlmnt_Dt, Disbursement_Dt, Auth_Amt, Settled_Amt, Refund_Txn_Id, Payment_Type, Card_Type, CC_Number, Billing_Postal_Code, Billing_Country, Shipping_Postal_Code, Shipping_Country, IP_Addr, Processor_Response_Code, Settlement_Currency) VALUES ('6kn2jyq6', 'sale', 'processor_declined', '', '', 8.03, 0.0, '', 'Credit Card', 'MasterCard', '##########', 'X', 'United States of America', '', '', '192.237.212.164', 2046.0, '');
INSERT INTO base_table_temp (Txn_Id, Txn_Type, Txn_Status, Sttlmnt_Dt, Disbursement_Dt, Auth_Amt, Settled_Amt, Refund_Txn_Id, Payment_Type, Card_Type, CC_Number, Billing_Postal_Code, Billing_Country, Shipping_Postal_Code, Shipping_Country, IP_Addr, Processor_Response_Code, Settlement_Currency) VALUES ('7b5gcaqa', 'sale', 'settled', '12/4/18', '12/5/18', 8.6, 8.6, '', 'Credit Card', 'MasterCard', '##########', 'X', 'United States of America', '', '', '192.237.212.164', 1000.0, 'USD');
INSERT INTO base_table_temp (Txn_Id, Txn_Type, Txn_Status, Sttlmnt_Dt, Disbursement_Dt, Auth_Amt, Settled_Amt, Refund_Txn_Id, Payment_Type, Card_Type, CC_Number, Billing_Postal_Code, Billing_Country, Shipping_Postal_Code, Shipping_Country, IP_Addr, Processor_Response_Code, Settlement_Currency) VALUES ('7nj2vdtb', 'sale', 'settled', '12/10/18', '12/11/18', 1.42, 1.42, '', 'Credit Card', 'MasterCard', '##########', 'X', 'United States of America', '', '', '192.237.212.164', 1000.0, 'USD');
INSERT INTO base_table_temp (Txn_Id, Txn_Type, Txn_Status, Sttlmnt_Dt, Disbursement_Dt, Auth_Amt, Settled_Amt, Refund_Txn_Id, Payment_Type, Card_Type, CC_Number, Billing_Postal_Code, Billing_Country, Shipping_Postal_Code, Shipping_Country, IP_Addr, Processor_Response_Code, Settlement_Currency) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO base_table_temp (Txn_Id, Txn_Type, Txn_Status, Sttlmnt_Dt, Disbursement_Dt, Auth_Amt, Settled_Amt, Refund_Txn_Id, Payment_Type, Card_Type, CC_Number, Billing_Postal_Code, Billing_Country, Shipping_Postal_Code, Shipping_Country, IP_Addr, Processor_Response_Code, Settlement_Currency) VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '')